version: '3.7'

services:
  replicator:
    build:
      context: ./
      dockerfile: Dockerfile.node
    image: insolar/mainnet-observer-node:local
    command:
      - /usr/local/bin/observer
      - --config
      - $PWD/.artifacts/observer.yaml
    ports:
      - 8085:8080
    volumes:
      - $PWD/observer.yaml:/observer.yaml
  api:
    build:
      context: ./
      dockerfile: Dockerfile.node
    image: insolar/mainnet-observer-node:local
    command:
      - /usr/local/bin/api
      - --config
      - $PWD/.artifacts/observerapi.yaml
    volumes:
      - $PWD/.artifacts/observerapi.yaml:/observerapi.yaml
    ports:
      - 8080:8080
  migrate:
    build:
      context: ./
      dockerfile: Dockerfile.node
    image: insolar/mainnet-observer-node:local
    command:
      - bash
      - -c
      - |
        for i in {1..10}; do
          /usr/local/bin/migrate --init --dir /migrations --config $PWD/.artifacts/migrate.yaml && break || sleep 1
        done
    volumes:
      - $PWD/.artifacts/migrate.yaml:/migrate.yaml
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "observer-node"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
