global:
  scrape_interval: 10s
  scrape_timeout: 2s

scrape_configs:

- job_name: observer
  static_configs:
  - targets:
    - "host.docker.internal:8888" # port observer must match with `listen` in observer.yaml
    labels:
      installation: local

